version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: npm
    versions:
    - 7.5.2
    - 7.5.4
    - 7.6.0
    - 7.6.3
    - 7.7.5
    - 7.7.6
    - 7.8.0
    - 7.9.0
  - dependency-name: rollup-plugin-visualizer
    versions:
    - 4.2.1
    - 4.2.2
    - 5.3.0
    - 5.3.4
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.44.0
    - 2.45.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.17.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.2
    - 4.17.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.2.0
    - 6.0.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
    - 7.13.13
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.10
    - 7.13.8
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.16
    - 7.13.0
    - 7.13.10
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
  - dependency-name: "@babel/plugin-external-helpers"
    versions:
    - 7.12.13
